# 2. NumPy 배열
* NumPy에는 **ndarray**라는 데이터 타입의 배열이 사용된다.
* 같은 타입의 데이터만 저장할 수 있다.
* Python list에 비해 계산 속도가 빠르다.

In [5]:
import numpy as np

# 2-1. 1차원 배열 만들기

In [6]:
# 1차원 배열 만들기
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
# type 확인
type(arr)

numpy.ndarray

In [8]:
# array 함수에는 data에 1개만 들어가야 함
# np.array(1,2,3,4,5) # Error

In [9]:
# 데이터 타입 확인
arr.dtype

dtype('int64')

In [10]:
# overflow 테스트
arr = np.array([2200000000,2,3,4], dtype=np.int32)
arr

array([-2094967296,           2,           3,           4], dtype=int32)

In [11]:
arr = np.array([1,2,3,4],dtype=float)
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float64


In [12]:
# shape: 각 차원의 배열의 size(차원의 모양)
arr.shape

(4,)

In [13]:
# size : 배열 전체의 요소의 개수
arr.size

4

In [14]:
# ndarray 에는 같은 데이터 타입만 들어가야 함
arr = np.array([1,2,3,3.14])
arr

array([1.  , 2.  , 3.  , 3.14])

In [15]:
# int, float -> in
arr = np.array([1,2,3,3.14], dtype=int)
arr

array([1, 2, 3, 3])

In [16]:
# int, float, string -. string
# > (big-endian), < (little-endian
# 32-character string
arr = np.array([1,3.14,'12345678901234567890123456789012332'])
arr

array(['1', '3.14', '12345678901234567890123456789012332'], dtype='<U35')

In [17]:
# 기존의 배열을 이용하여 타입이 다른 배열을 새성하기
new_arr = arr.astype(float)
new_arr

array([1.00000000e+00, 3.14000000e+00, 1.23456789e+34])

In [18]:
arr.dtype, new_arr.dtype

(dtype('<U35'), dtype('float64'))

# 2차원 배열 생성하기


In [19]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
type(arr2)

numpy.ndarray

In [21]:
arr2.dtype, arr2.shape, arr2.size, arr2.ndim

(dtype('int64'), (3, 4), 12, 2)

In [22]:
new_arr2 = arr2.astype(int)
new_arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])


# 2-2.np.arange()

## 1차원 배열 생성하기

In [23]:
for i in range(1,11,2): # 1,3,5,7,9
    print(i)

1
3
5
7
9


In [24]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [26]:
 np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : integer or real
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : integer or real, optional
    Spacing between values.  For any output `out`, this is the distance
  

## 2차원 배열 생성하기

In [27]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
print(arr.reshape(3,4))
print(arr.reshape((3,4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
# 원본 배열을 변경
arr.shape = (3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 2-3. np.zeros() 함수로 생성


In [30]:
arr = np.zeros(4, dtype=int)
arr

array([0, 0, 0, 0])

In [31]:
arr2 = np.zeros((3,4), dtype=int)
arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# 2-4. np.ones() 함수로 생성


In [32]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [33]:
arr2 = np.ones((3,4), dtype=int)
arr2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# 2-5. np.linspace() 함수로 생성


In [34]:
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [50]:
arr = np.linspace(0, 10, 50)
arr

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [36]:
arr.shape

(50,)

In [37]:
# (5,10) 인 2차원 배열로 만들기
arr2 = arr.reshape((5,10))
arr2

array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
       [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
       [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
         5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
       [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
       [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]])

# 2-6. np.full() 함수로 생성


In [38]:
arr = np.full((4,), 10)
arr

array([10, 10, 10, 10])

In [39]:
arr2 = np.full((3,4),10)
arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

# 2-7. np.eye() 함수로 생성


In [40]:
# 단위 행렬, 항등 행렬
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 2-8. np.random으로 생성

In [41]:
arr = np.random.rand(5)
arr

array([0.00945546, 0.20689769, 0.69175472, 0.48238392, 0.31691771])

In [42]:
arr2 = np.random.rand(2,3)
arr2

array([[0.15343312, 0.89013865, 0.53146213],
       [0.10665353, 0.79459452, 0.97438435]])

In [43]:
arr = np.random.randint(5, size=5) # 0~4
arr

array([1, 0, 3, 1, 0])

In [44]:
arr = np.random.randint(5, size=(3,4)) # 0~4
arr

array([[4, 0, 3, 1],
       [3, 2, 3, 0],
       [3, 4, 0, 3]])

In [45]:
np.random.seed(123)
np.random.rand(2,3)

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

# 2-9. Numpy 배열 Save & Load

In [46]:
arr = np.arange(0,5) # 0~4
arr

array([0, 1, 2, 3, 4])

In [47]:
np.save('my_arr', arr)

In [48]:
new_arr = np.load('my_arr.npy')
new_arr

array([0, 1, 2, 3, 4])

In [90]:
arr = np.empty([2,3])
arr

array([[0.15343312, 0.89013865, 0.53146213],
       [0.10665353, 0.79459452, 0.97438435]])