# 3. 연산
## 3-1. 산술연산


In [4]:
import numpy as np

In [6]:
# 1차원 배열
a = np.arange(1,5) # 1~4
b = np.arange(5,9) # 5~8


In [8]:
a, b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [10]:
# shape 이 같아야 함
a + b

array([ 6,  8, 10, 12])

In [12]:
a - b

array([-4, -4, -4, -4])

In [14]:
a * b

array([ 5, 12, 21, 32])

In [16]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [18]:
# 2차원 배열
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)

a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [20]:
a+b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [22]:
a-b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [24]:
# 단순 곱셈 (이렇게는 안쓰임)
a*b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [26]:
a/b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

## 행렬의 곱셈 (dot product)

In [28]:
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [30]:
b = np.arange(7,13).reshape(3,2)
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [32]:
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]]))

In [34]:
c = np.dot(a,b)
c

array([[ 58,  64],
       [139, 154]])

In [36]:
1*7 + 2*9 + 3*11

58

In [38]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

## 배열과 스칼라(숫자)와의 연산 (Broadcasting)

In [40]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [42]:
a + 3

array([4, 5, 6])

In [44]:
a - 3

array([-2, -1,  0])

In [46]:
a * 3

array([3, 6, 9])

In [48]:
a / 3

array([0.33333333, 0.66666667, 1.        ])

## 3-2. Aggregation 함수

### 1차원 배열

In [50]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [52]:
# max 값 찾기
np.max(a)

5

In [54]:
# min 값 찾기
np.min(a)

1

In [56]:
a.max(), a.min()

(5, 1)

In [58]:
# sum 값 구하기
np.sum(a)

15

In [60]:
# 평균값 구하기
np.mean(a)

3.0

In [62]:
# 이상치(outlier)가 있는 경우 
# 평균값이 이 배열의 데이터를 잘 대표한다고 볼 수 있을까?
b = np.array([1,2,3,4,100]) 
b

array([  1,   2,   3,   4, 100])

In [64]:
# 중앙값(median), 중위값
np.median(b)

3.0

In [66]:
# 데이터가 짝수개인 경우
b = np.array([1,3,5,100])
np.median(b)

4.0

In [68]:
# 표준편차 (standard deviation)
np.std(a)

1.4142135623730951

### 2차원 배열

In [70]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.max(a), a.max()

(6, 6)

In [74]:
np.min(a), a.min()

(1, 1)

In [76]:
# 2차원의 배열의 경우 axis를 주어 각 행과 열의 max 값을 구할 수 있음
np.max(a, axis=0) # 행(row)

array([4, 5, 6])

In [78]:
np.max(a, axis=1) # 열(column)

array([3, 6])

In [80]:
np.sum(a)

21

In [82]:
np.sum(a, axis=0)

array([5, 7, 9])

In [84]:
np.sum(a, axis=1)

array([ 6, 15])

## 비교 (Comparison)

In [86]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [88]:
a >= 3

array([False, False,  True,  True,  True])

In [90]:
a == 3

array([False, False,  True, False, False])

In [92]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [94]:
# cumsum: 배열에서 주어진 축에 따라 누적되는 원소들의 누적 합을 계산하는 함수
# cumsum, corrcoef(상관계수) 구하기
np.cumsum(a)

array([ 1,  3,  6, 10, 15])