# 4-1. 1차원 배열

In [2]:
import numpy as np

In [19]:
np.random.seed(100)
arr = np.random.randint(1,10,size=10)
arr

array([9, 9, 4, 8, 8, 1, 5, 3, 6, 3])

In [20]:
# 오름차순 정렬
np.sort(arr)

array([1, 3, 3, 4, 5, 6, 8, 8, 9, 9])

In [22]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([9, 9, 8, 8, 6, 5, 4, 3, 3, 1])

In [23]:
# 정렬 시 주의사항
arr.sort() # 바로 원본 배열이 sort됨.  # 권장 X
arr 

array([1, 3, 3, 4, 5, 6, 8, 8, 9, 9])

# 4-2. 2차원 배열

In [26]:
np.random.seed(100)
arr2 = np.random.randint(1,10,size=(3,4)) # 1~9, size=(3,4)
arr2

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3]])

In [27]:
np.sort(arr2)

array([[4, 8, 9, 9],
       [1, 3, 5, 8],
       [3, 3, 3, 6]])

In [28]:
np.sort(arr2) # sort(arr2, axis=1) 과 동일

array([[4, 8, 9, 9],
       [1, 3, 5, 8],
       [3, 3, 3, 6]])

In [29]:
np.sort(arr2, axis=0)

array([[6, 1, 3, 3],
       [8, 3, 4, 3],
       [9, 9, 5, 8]])

In [30]:
arr2

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3]])

In [32]:
# index를 반환하는 argsort
np.argsort(arr2)

array([[2, 3, 0, 1],
       [1, 3, 2, 0],
       [1, 2, 3, 0]], dtype=int64)

In [33]:
np.argsort(arr2, axis=0)

array([[2, 1, 2, 1],
       [1, 2, 0, 2],
       [0, 0, 1, 0]], dtype=int64)