In [ ]:
# 5. 인덱싱과 슬라이싱

In [41]:
import numpy as np

In [42]:
arr = np.arange(1,11) # 1~10
arr[0], arr[4], arr[9]

(1, 5, 10)

In [43]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
arr2[0][1], arr2[1][2], arr2[2][3]

(2, 7, 12)

In [45]:
arr2[0,1], arr2[1,2], arr2[2,3] # numpy에서는 다차언 indexing

(2, 7, 12)

In [46]:
arr2[-1][-2]

11

# 5-2. 슬라이싱

### 1차원 배열

In [47]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
# 3~끝까지 슬라이싱
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr[2:5]

array([3, 4, 5])

In [50]:
# 처음~5까지 슬라이싱
arr[:5]

array([1, 2, 3, 4, 5])

In [51]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
# 슬라이싱을 한 후에 값을 변경하면 원본에 영향을 미칠까?
new_arr = arr[:5]
new_arr

array([1, 2, 3, 4, 5])

In [53]:
new_arr[0] = 100
new_arr

array([100,   2,   3,   4,   5])

In [54]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [55]:
import numpy as np
copy_arr = np.copy(arr)
copy_arr    

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [57]:
copy_arr[0] = 101
copy_arr

array([101,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [58]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

### 2차원 배열

In [16]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
# 첫번째 행을 모두 가져오기
arr2[0,:] #arr2[0]

array([1, 2, 3, 4])

In [18]:
# 세번째 열을 모두 가져오기
arr2[:,2]

array([ 3,  7, 11])

In [19]:
# 첫번째, 두번째 행을 모두 가져오기
arr2[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
# 두번째, 세번째 열을 모두 가져오기
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [21]:
# [[2,3]
#   [6,7]]
arr2[:2, 1:3]

array([[2, 3],
       [6, 7]])

## 5-3. Fancy 인덱싱

In [22]:
# 1차원 배열
arr[0] = 1
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:

# 1,3,5 로 된 배열을 만들기
np.array([arr[0],arr[2], arr[4]])

array([1, 3, 5])

In [24]:
# 슬라이싱 [start:end:step]
arr[:5:2]

array([1, 3, 5])

In [25]:
# Fancy 인덱싱
arr[[0,2,4]]

array([1, 3, 5])

In [26]:
# 2차원 배열
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
np.array([arr2[0],arr2[2]])

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [28]:
# Fancy 인덱싱
arr2[[0,2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [29]:
# 주의 
arr2[0,2] # arr2[0][2]

3

In [30]:
# 슬라이싱
arr2[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## 5-4. Boolean 인덱싱

In [31]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [32]:
cond = [False, True, False, False,True]
arr[cond]

array([1, 4])

In [33]:
arr[[False, True, False, False,True]]

array([1, 4])

In [34]:
arr > 2

array([False, False, False,  True,  True])

In [35]:
arr[arr>2]

array([3, 4])

In [36]:
# 짝수만 뽑기
arr % 2 == 0

array([ True, False,  True, False,  True])

In [37]:
arr[arr % 2 == 0]

array([0, 2, 4])

In [38]:
# 0, 3. 4
(arr < 1) | (arr > 2)
arr[(arr < 1) | (arr > 2)]

array([0, 3, 4])

In [39]:
# 2, 3
(arr > 1) & (arr < 4)
arr[(arr > 1) & (arr < 4)]

array([2, 3])