# 6. 실습

In [3]:
# numpy import하기
import numpy as np

## 6-1. NumPy 배열 생성

In [3]:
# np.array()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [8]:
# 1차원 배열의 데이터타입, 모양, 배열 전체 element의 수, 차원의 수 출력하기
arr.dtype, arr.shape, arr.size, arr.ndim

(dtype('int32'), (5,), 5, 1)

In [9]:
# np.array()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
arr2 = np.array([[10,20,30,40],[50,60,70,80]])
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [11]:
# np.arange()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [14]:
# np.arange()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
arr2 = np.arange(10,90,10).reshape(2,4)
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [29]:
# 주사위를 100번 던져서 나오는 숫자 배열 출력하기
arr = np.random.randint(6, size=100) + 1
arr

array([3, 1, 6, 1, 5, 2, 3, 6, 2, 5, 3, 3, 4, 5, 4, 6, 4, 2, 2, 6, 2, 1,
       3, 5, 6, 5, 5, 4, 4, 6, 4, 5, 4, 5, 6, 3, 1, 5, 5, 2, 6, 6, 4, 3,
       6, 1, 4, 2, 5, 4, 1, 6, 3, 1, 6, 2, 2, 1, 5, 6, 3, 3, 1, 5, 6, 5,
       4, 5, 1, 1, 3, 2, 1, 2, 4, 3, 6, 1, 1, 4, 6, 1, 1, 6, 4, 3, 1, 2,
       2, 5, 1, 1, 4, 1, 5, 1, 2, 6, 4, 2])

In [31]:
# np.random을 사용하여 랜덤 실수값으로 이루어진 (3, 4) 2차원 배열 생성
arr = np.random.rand(12).reshape(3,4)
arr

array([[0.88288184, 0.78026223, 0.35618642, 0.82093201],
       [0.38133986, 0.33308267, 0.05311422, 0.69744862],
       [0.86813055, 0.64551466, 0.3634527 , 0.11088103]])

## 6-2. 산술연산

In [33]:
# [1, 2, 3, 4, 5], [6, 7, 8, 9, 10] 1차원 배열 2개를 생성하고 출력하기
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)
arr1, arr2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [34]:
# 1차원 배열간 산술연산(덧셈, 뺄셈, 곱셈, 나눗셈) 하기
arr1+arr2, arr1-arr2, arr1*arr2, arr1/arr2

(array([ 7,  9, 11, 13, 15]),
 array([-5, -5, -5, -5, -5]),
 array([ 6, 14, 24, 36, 50]),
 array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]))

In [36]:
# [[1, 2, 3, 4, 5]   [[11, 12, 13, 14, 15]
#  [6, 7, 8, 9, 10]], [16, 17, 18, 19, 20]] 2차원 배열 2개를 생성하고 출력하기
arr1 = np.arange(1,11).reshape(2,5)
arr2 = np.arange(11,21).reshape(2,5)
arr1, arr2

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]))

In [37]:
# 2차원 배열간 산술연산(덧셈, 뺄셈, 나눗셈) 하기
arr1+arr2, arr1-arr2, arr1*arr2, arr1/arr2

(array([[12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30]]),
 array([[-10, -10, -10, -10, -10],
        [-10, -10, -10, -10, -10]]),
 array([[ 11,  24,  39,  56,  75],
        [ 96, 119, 144, 171, 200]]),
 array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
        [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]]))

In [41]:
# 두번째 배열의 shape을 (5, 2)로 만들고 출력하기
arr2 = arr2.reshape(5,2)
arr2

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [42]:
# 행렬곱셈(dot product) 연산하기
np.dot(arr1, arr2)

array([[245, 260],
       [620, 660]])

## 6-3. Aggregation 함수

In [45]:
# 1~10까지 이루어진 1차원 배열 생성하기
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
# 최대값, 최소값 출력하기
arr.max(), arr.min()

(10, 1)

In [48]:
# 배열요소의 합, 평균값 출력하기
arr.sum(), arr.mean()

(55, 5.5)

In [51]:
# 중앙값(중위값), 표준편차 출력하기
np.median(arr), arr.std()

(5.5, 2.8722813232690143)

In [54]:
# 1~20까지 이루어진 2차원 배열 (4, 5) 생성하기
arr = np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [58]:
# 각 행의 max값, min값 출력하기
np.max(arr, axis=1), np.min(arr, axis=1)

(array([ 5, 10, 15, 20]), array([ 1,  6, 11, 16]))

In [59]:
# 각 열의 max값, min값 출력하기
np.max(arr, axis=0), np.min(arr, axis=0)

(array([16, 17, 18, 19, 20]), array([1, 2, 3, 4, 5]))

In [60]:
# 각 행의 sum값 출력하기
np.sum(arr, axis=1)

array([15, 40, 65, 90])

In [61]:
# 각 열의 sum값 출력하기
np.sum(arr, axis=0)

array([34, 38, 42, 46, 50])

## 6-4. 정렬

In [70]:
# 1~100까지 랜덤 정수값을 갖는 1차원 배열 (10, ) 생성하기
# seed값 100부여하기
np.random.seed(100)
arr = np.random.randint(1,101, size = 10)
arr

array([ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99])

In [76]:
# 위 1차원 배열을 오름차순 정렬하기
np.sort(arr)

array([ 9, 11, 25, 49, 53, 68, 80, 88, 95, 99])

In [79]:
# 위 1차원 배열을 내림차순 정렬하기
np.sort(arr)[::-1]

array([99, 95, 88, 80, 68, 53, 49, 25, 11,  9])

In [81]:
# 랜덤 seed값 100부여하기
# 1~100까지 랜덤 정수값을 갖는 2차원 배열 (5, 10) 생성하기
np.random.seed(100)
arr = np.random.randint(1,101, size=50).reshape(5,10)
arr

array([[ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99],
       [54, 67, 99, 15, 35, 25, 16, 61, 59, 17],
       [10, 94, 87,  3, 28,  5, 32,  2, 14, 84],
       [ 5, 92, 60, 68,  8, 50, 48, 66, 62, 15],
       [56, 72, 81,  3, 95, 20, 99, 64, 54, 28]])

In [82]:
# 열 기준 정렬하기
np.sort(arr, axis=0)

array([[ 5, 25, 60,  3,  8,  5, 11,  2, 14, 15],
       [ 9, 67, 68,  3, 28, 20, 16, 61, 53, 17],
       [10, 72, 81, 15, 35, 25, 32, 64, 54, 28],
       [54, 92, 87, 68, 80, 49, 48, 66, 59, 84],
       [56, 94, 99, 88, 95, 50, 99, 95, 62, 99]])

In [83]:
# 행 기준 정렬하기
np.sort(arr, axis=1)

array([[ 9, 11, 25, 49, 53, 68, 80, 88, 95, 99],
       [15, 16, 17, 25, 35, 54, 59, 61, 67, 99],
       [ 2,  3,  5, 10, 14, 28, 32, 84, 87, 94],
       [ 5,  8, 15, 48, 50, 60, 62, 66, 68, 92],
       [ 3, 20, 28, 54, 56, 64, 72, 81, 95, 99]])

## 6-5. 인덱싱과 슬라이싱

In [4]:
# 0~14로 이루어진 2차원 배열 (3, 5) 생성하기
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [85]:
# 위 배열에서 7을 인덱싱하기
arr[1][2]

7

In [87]:
# 위 배열에서 14를 인덱싱하기 (음수 인덱스 사용)
arr[-1][-1]

14

In [89]:
# 위 배열에서 배열 [6, 7]을 슬라이싱하기
arr[1,1:3]

array([6, 7])

In [11]:
# 위 배열에서 배열 [7, 12]을 슬라이싱하기
arr[1:3, 2]

array([ 7, 12])

In [13]:
# 위 배열에서 [[3, 4], [8, 9]]을 슬라이싱하기
arr[:2, 3:5]

array([[3, 4],
       [8, 9]])

In [7]:
# 위 배열에서 3의 배수 찾기
arr[(arr%3 == 0) & (arr != 0)]

array([ 3,  6,  9, 12])

In [9]:
# 위 배열에서 4로 나누면 1이 남는 수 찾기
arr[arr %4 == 1]

array([ 1,  5,  9, 13])

In [10]:
# 위 배열에서 3의 배수이면서 4로 나누면 1이 남는 수 찾기
arr[(arr % 3 == 0) & (arr % 4 == 1)]

array([9])